site_name: OWASP Developer Guide
site_description: OWASP Foundation Developer Guide project
site_author: OWASP Developer Guide team
site_url: https://devguide.owasp.org/

copyright: Licensed under the <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution Share Alike 4.0 International license</a>.

repo_name: OWASP/DevGuide
repo_url: https://github.com/OWASP/DevGuide

theme:
  name: material
  language: en
  logo: assets/images/dg_logo.png
  favicon: assets/images/favicon.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - def_list

plugins:
  - open-in-new-tab  

nav:
  - Introduction: index.md
  - Manifesto: manifesto.md
  - Principles:
    - 1. Be passionate about security: principles/01_Be_passionate_about_security.md
    - 2. Start with a clear vision for your program: principles/02_Start_with_a_clear_vision_for_your_program.md
    - 3. Secure management support: principles/03_Secure_management_support.md
    - 4. Nominate a dedicated captain: principles/04_Nominate_a_dedicated_captain.md
    - 5. Trust your champions: principles/05_Trust_your_champions.md
    - 6. Create a community: principles/06_Create_a_community.md
    - 7. Promote knowledge sharing: principles/07_Promote_knowledge_sharing.md
    - 8. Reward responsibility: principles/08_Reward_responsibility.md
    - 9. Invest in your champions: principles/09_Invest_in_your_champions.md
    - 10. Anticipate personnel changes: principles/10_Anticipate_personnel_changes.md
  - Artifacts: artifacts.md
  - Team: team.md
  - References: references.md
  - Project page: https://owasp.org/www-project-security-champions-guidebook/
  - LinkedIn: https://www.linkedin.com/company/owasp-security-champions-guide/
  - Hall of Fame: halloffame.md